/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf -o test.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/scene.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="wszystko_z_dziura66glb">
          <group name="Sketchfab_model" position={[9.286, 0, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.663}>
            <group name="805bd594c0894f9984171f21377f43aeobjcleanergles">
              <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials.palette} position={[56.994, -6.81, -0.408]} />
            </group>
          </group>
          <group name="Low_Poly_Simple_Urban_City_3D_Asset_Pack" position={[214.458, 0, -4.592]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.591}>
            <group name="Buildings" position={[-0.796, 217.258, 0.047]} rotation={[0, 0, -Math.PI]}>
              <mesh name="Building_2" geometry={nodes.Building_2.geometry} material={materials.Mat} position={[45.022, -202.368, 0.512]} rotation={[0, 0, Math.PI / 2]} scale={[1.052, 1.026, 0.937]} />
              <mesh name="Building_3" geometry={nodes.Building_3.geometry} material={materials.Mat} position={[-6.021, -200.426, 0.4]} rotation={[0, 0, Math.PI]} scale={[1.026, 1.052, 1.483]} />
              <mesh name="Building_4" geometry={nodes.Building_4.geometry} material={materials.Mat} position={[-30.065, -143.599, 0.645]} rotation={[0, 0, Math.PI]} scale={[1.446, 1.41, 1.228]} />
              <mesh name="Building_5" geometry={nodes.Building_5.geometry} material={materials.Mat} position={[-5.235, -142.619, 0.376]} rotation={[0, 0, Math.PI]} scale={[1.052, 1.026, 1]} />
              <mesh name="Building_6" geometry={nodes.Building_6.geometry} material={materials.Mat} position={[-29.864, -107.426, 0.376]} rotation={[0, 0, -Math.PI / 2]} scale={[1.41, 1.446, 1.374]} />
              <mesh name="Building_7" geometry={nodes.Building_7.geometry} material={materials.Mat} position={[-30.733, -199.626, 0.323]} rotation={[0, 0, -Math.PI]} scale={[1.026, 1.052, 1]} />
              <mesh name="Building_7001" geometry={nodes.Building_7001.geometry} material={materials.Mat} position={[63.032, -199.889, 0.323]} rotation={[0, 0, -Math.PI]} scale={[1.026, 1.052, 1.049]} />
              <mesh name="Building_9" geometry={nodes.Building_9.geometry} material={materials.Mat} position={[-5.287, -105.414, 0.376]} rotation={[0, 0, 3.125]} scale={[1.052, 1.026, 1]} />
            </group>
            <group name="Props" position={[2.389, 147.714, -0.033]}>
              <group name="Boxes" position={[51.814, 11.143, 0.08]} rotation={[0, 0, -Math.PI]} />
              <group name="Other" position={[35.411, -5.107, 0.08]}>
                <mesh name="Hydrant" geometry={nodes.Hydrant.geometry} material={materials.Mat} position={[0.434, 163.511, -0.285]} rotation={[0, 0, -Math.PI / 2]} />
                <mesh name="Light" geometry={nodes.Light.geometry} material={materials.Mat} position={[-45.21, 161.938, 0]} rotation={[0, 0, Math.PI / 2]} />
                <mesh name="Light001" geometry={nodes.Light001.geometry} material={materials.Mat} position={[5.563, 161.938, 0]} rotation={[0, 0, Math.PI / 2]} />
                <mesh name="Light002" geometry={nodes.Light002.geometry} material={materials.Mat} position={[5.563, 234.741, 0]} rotation={[0, 0, -Math.PI / 2]} />
                <mesh name="Light003" geometry={nodes.Light003.geometry} material={materials.Mat} position={[-45.21, 234.741, 0]} rotation={[0, 0, -Math.PI / 2]} />
                <mesh name="Light004" geometry={nodes.Light004.geometry} material={materials.Mat} position={[-45.21, 264.445, 0]} rotation={[0, 0, Math.PI / 2]} />
                <mesh name="Light005" geometry={nodes.Light005.geometry} material={materials.Mat} position={[5.563, 264.445, 0]} rotation={[0, 0, Math.PI / 2]} />
                <mesh name="Light006" geometry={nodes.Light006.geometry} material={materials.Mat} position={[-76.44, 161.938, 0]} rotation={[0, 0, Math.PI / 2]} />
                <mesh name="Light007" geometry={nodes.Light007.geometry} material={materials.Mat} position={[-76.209, 234.741, 0]} rotation={[0, 0, -Math.PI / 2]} />
                <mesh name="Light009" geometry={nodes.Light009.geometry} material={materials.Mat} position={[-76.363, 264.445, 0]} rotation={[0, 0, Math.PI / 2]} />
                <mesh name="Tram_Stop" geometry={nodes.Tram_Stop.geometry} material={materials.Mat} position={[-100.973, 163.354, 0]} rotation={[0, 0, Math.PI / 2]} />
                <mesh name="Trash_Big" geometry={nodes.Trash_Big.geometry} material={materials.Mat} position={[-2.645, 205.6, 0]} rotation={[0, 0, Math.PI / 2]} />
                <mesh name="Trash_Big001" geometry={nodes.Trash_Big001.geometry} material={materials.Mat} position={[-6.454, 204.515, 0]} rotation={[0, 0, 1.942]} />
                <mesh name="Trash_Big002" geometry={nodes.Trash_Big002.geometry} material={materials.Mat} position={[-42.385, 272.405, 0]} rotation={[0, 0, 0.303]} />
                <mesh name="Tree_1" geometry={nodes.Tree_1.geometry} material={materials.Mat} position={[8.148, 210.149, -0.333]} rotation={[0, 0, -Math.PI]} />
                <mesh name="Tree_1001" geometry={nodes.Tree_1001.geometry} material={materials.Mat} position={[8.148, 189.621, -0.333]} />
                <mesh name="Tree_1002" geometry={nodes.Tree_1002.geometry} material={materials.Mat} position={[-47.364, 210.149, -0.359]} rotation={[0, 0, -Math.PI]} />
                <mesh name="Tree_1003" geometry={nodes.Tree_1003.geometry} material={materials.Mat} position={[-47.364, 189.621, -0.359]} />
                <mesh name="Tree_2" geometry={nodes.Tree_2.geometry} material={materials.Mat} position={[8.148, 220.149, -0.333]} rotation={[0, 0, -Math.PI]} />
                <mesh name="Tree_2001" geometry={nodes.Tree_2001.geometry} material={materials.Mat} position={[8.148, 179.621, -0.333]} />
                <mesh name="Tree_2002" geometry={nodes.Tree_2002.geometry} material={materials.Mat} position={[-47.364, 220.149, -0.359]} rotation={[0, 0, -Math.PI]} />
                <mesh name="Tree_2003" geometry={nodes.Tree_2003.geometry} material={materials.Mat} position={[-47.364, 179.621, -0.359]} />
              </group>
              <group name="Road_Signs" position={[-83.186, 11.143, -0.322]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh name="Road_Barrier" geometry={nodes.Road_Barrier.geometry} material={materials.Mat} position={[-175.995, 51.491, 0.402]} />
                <mesh name="Road_Work_Sign_1" geometry={nodes.Road_Work_Sign_1.geometry} material={materials.Mat} position={[-159.026, 52.574, 0.402]} />
                <mesh name="Road_Work_Sign_2" geometry={nodes.Road_Work_Sign_2.geometry} material={materials.Mat} position={[-173.712, 55.396, 0.402]} />
                <mesh name="Traffic_Light_1" geometry={nodes.Traffic_Light_1.geometry} material={materials.Mat} position={[-142.638, 69.092, 0.402]} />
                <mesh name="Traffic_Light_1001" geometry={nodes.Traffic_Light_1001.geometry} material={materials.Mat} position={[-142.51, 127.949, 0.402]} rotation={[0, 0, Math.PI / 2]} />
                <mesh name="Traffic_Light_1002" geometry={nodes.Traffic_Light_1002.geometry} material={materials.Mat} position={[-119.921, 69.217, 0.402]} rotation={[0, 0, -Math.PI / 2]} />
                <mesh name="Traffic_Light_1004" geometry={nodes.Traffic_Light_1004.geometry} material={materials.Mat} position={[-142.475, 46.428, 0.402]} rotation={[0, 0, Math.PI / 2]} />
                <mesh name="Traffic_Light_2" geometry={nodes.Traffic_Light_2.geometry} material={materials.Mat} position={[-221.739, 69.083, 0.402]} rotation={[0, 0, Math.PI]} />
                <mesh name="Traffic_Light_2001" geometry={nodes.Traffic_Light_2001.geometry} material={materials.Mat} position={[-243.97, 46.683, 0.402]} />
                <mesh name="Traffic_Light_2002" geometry={nodes.Traffic_Light_2002.geometry} material={materials.Mat} position={[-221.654, 128.556, 0.402]} rotation={[0, 0, Math.PI / 2]} />
              </group>
            </group>
            <group name="Road" position={[-0.796, 526.983, -0.061]} rotation={[0, 0, -Math.PI]}>
              <mesh name="Road_1001" geometry={nodes.Road_1001.geometry} material={materials.Mat} position={[22.181, 180.97, -0.168]} scale={[1, 3.082, 1]} />
              <mesh name="Road_2001" geometry={nodes.Road_2001.geometry} material={materials.Mat} position={[-18.578, 135.164, -0.211]} rotation={[0, 0, Math.PI / 2]} scale={[1, 2.079, 1]} />
              <mesh name="Road_2002" geometry={nodes.Road_2002.geometry} material={materials.Mat} position={[63.084, 135.159, -0.211]} rotation={[0, 0, Math.PI / 2]} scale={[1, 1.994, 1]} />
              <mesh name="Road_2003" geometry={nodes.Road_2003.geometry} material={materials.Mat} position={[22.194, 99.151, -0.212]} />
              <mesh name="Road_2004" geometry={nodes.Road_2004.geometry} material={materials.Mat} position={[-18.676, 236.999, -0.212]} rotation={[0, 0, Math.PI / 2]} scale={[1, 2.05, 1]} />
              <mesh name="Road_2005" geometry={nodes.Road_2005.geometry} material={materials.Mat} position={[62.944, 236.966, -0.212]} rotation={[0, 0, Math.PI / 2]} scale={[1, 1.964, 1]} />
              <mesh name="Road_Crossroads_2" geometry={nodes.Road_Crossroads_2.geometry} material={materials.Mat} position={[22.181, 135.148, -0.212]} />
              <mesh name="Road_Crossroads_2001" geometry={nodes.Road_Crossroads_2001.geometry} material={materials.Mat} position={[22.181, 236.978, -0.212]} />
              <mesh name="Road_Crossroads_4002" geometry={nodes.Road_Crossroads_4002.geometry} material={materials.Mat} position={[-71.683, 135.203, -0.278]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={[-2.067, -1, -1]} />
              <mesh name="Road_Crossroads_4003" geometry={nodes.Road_Crossroads_4003.geometry} material={materials.Mat} position={[-71.699, 236.339, -0.296]} rotation={[0, 0, -Math.PI / 2]} scale={[2.376, 1, 1]} />
              <mesh name="Road_Crossroads_4004" geometry={nodes.Road_Crossroads_4004.geometry} material={materials.Mat} position={[-59.557, 135.161, -0.188]} rotation={[0, 0, -Math.PI / 2]} />
              <mesh name="Road_Crossroads_4005" geometry={nodes.Road_Crossroads_4005.geometry} material={materials.Mat} position={[-59.566, 186.005, -0.169]} rotation={[0, 0, -Math.PI / 2]} scale={[5.74, 1, 1]} />
              <mesh name="Road_Crossroads_4008" geometry={nodes.Road_Crossroads_4008.geometry} material={materials.Mat} position={[21.89, 249.102, -0.27]} rotation={[0, 0, Math.PI]} scale={[2.227, 1, 1]} />
              <mesh name="Road_Crossroads_4009" geometry={nodes.Road_Crossroads_4009.geometry} material={materials.Mat} position={[-59.545, 237, -0.188]} rotation={[0, 0, -Math.PI / 2]} />
              <mesh name="Road_Stopline_2" geometry={nodes.Road_Stopline_2.geometry} material={materials.Mat} position={[-3.772, 135.142, -0.212]} rotation={[0, 0, -Math.PI / 2]} />
              <mesh name="Road_Stopline_2001" geometry={nodes.Road_Stopline_2001.geometry} material={materials.Mat} position={[-33.584, 135.16, -0.212]} rotation={[0, 0, Math.PI / 2]} />
              <mesh name="Road_Stopline_2002" geometry={nodes.Road_Stopline_2002.geometry} material={materials.Mat} position={[48.126, 135.156, -0.212]} rotation={[0, 0, Math.PI / 2]} />
              <mesh name="Road_Stopline_2003" geometry={nodes.Road_Stopline_2003.geometry} material={materials.Mat} position={[22.196, 109.157, -0.212]} />
              <mesh name="Road_Stopline_2004" geometry={nodes.Road_Stopline_2004.geometry} material={materials.Mat} position={[-3.772, 236.98, -0.212]} rotation={[0, 0, -Math.PI / 2]} />
              <mesh name="Road_Stopline_2005" geometry={nodes.Road_Stopline_2005.geometry} material={materials.Mat} position={[-33.584, 236.999, -0.212]} rotation={[0, 0, Math.PI / 2]} />
              <mesh name="Road_Stopline_2006" geometry={nodes.Road_Stopline_2006.geometry} material={materials.Mat} position={[48.126, 236.966, -0.212]} rotation={[0, 0, Math.PI / 2]} />
            </group>
            <group name="Vehicles" position={[-0.796, 57.47, 0.047]}>
              <group name="Buses" position={[-74.845, -19.601, 0]} rotation={[0, 0, -Math.PI / 2]} />
              <group name="Cars" position={[37.5, 21.001, 0]} rotation={[0, 0, -Math.PI / 2]} />
              <group name="Emergency_Vehicles" position={[-17.364, -8, 0]} />
              <group name="Main_Hero_Trucks" position={[7.655, -19.601, 0]} rotation={[0, 0, -Math.PI / 2]} />
              <group name="Pickups" position={[-82.5, 21.001, 0]} rotation={[0, 0, -Math.PI / 2]} />
              <group name="Trams" position={[-2.124, -56.623, 0]} rotation={[0, 0, -Math.PI]} />
              <group name="Trucks" position={[75.155, -19.601, 0]} rotation={[0, 0, -Math.PI / 2]} />
            </group>
          </group>
          <group name="Low_Poly_Simple_Urban_City_3D_Asset_Pack001" position={[167.246, 0, -4.592]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.591}>
            <group name="Road001" position={[-0.796, 526.983, -0.061]} rotation={[0, 0, -Math.PI]} />
          </group>
          <group name="Low_Poly_Simple_Urban_City_3D_Asset_Pack002" position={[214.458, 0, -79.868]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.591}>
            <group name="Road002" position={[-0.796, 526.983, -0.061]} rotation={[0, 0, -Math.PI]}>
              <mesh name="Road_Crossroads_4006" geometry={nodes.Road_Crossroads_4006.geometry} material={materials['Mat.002']} position={[-187.001, 104.294, -0.17]} rotation={[0, 0, -Math.PI / 2]} scale={[1.877, 1, 1]} />
            </group>
          </group>
          <group name="Low_Poly_Simple_Urban_City_3D_Asset_Pack003" position={[214.458, 0, -4.592]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.591}>
            <group name="Road003" position={[-0.796, 526.983, -0.061]} rotation={[0, 0, -Math.PI]}>
              <mesh name="Road_Stopline_1001" geometry={nodes.Road_Stopline_1001.geometry} material={materials['Mat.003']} position={[22.181, 161.129, -0.212]} rotation={[0, 0, Math.PI]} />
            </group>
          </group>
          <group name="Low_Poly_Simple_Urban_City_3D_Asset_Pack004" position={[-248.407, 0, -31.734]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.591}>
            <group name="Road004" position={[-0.796, 526.983, -0.061]} rotation={[0, 0, -Math.PI]}>
              <mesh name="Road_Stopline_1005" geometry={nodes.Road_Stopline_1005.geometry} material={materials['Mat.004']} position={[22.181, 59.288, -0.212]} rotation={[0, 0, Math.PI]} />
            </group>
          </group>
          <group name="Low_Poly_Simple_Urban_City_3D_Asset_Pack005" position={[177.049, 0, -26.293]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.591}>
            <group name="Road005" position={[-0.796, 526.983, -0.061]} rotation={[0, 0, -Math.PI]} />
          </group>
          <mesh name="Cube" geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[-13.396, 50.967, -13.474]} rotation={[0, -Math.PI / 2, 0]} scale={[11.158, 3.774, 4.456]} />
          <mesh name="Road_Roadworks" geometry={nodes.Road_Roadworks.geometry} material={materials['Mat.001']} position={[21.93, 0.104, -18.164]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.591} />
          <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[-75.714, 44.142, 1.848]} rotation={[0, -1.435, 0]} scale={[11.158, 3.774, 4.456]} />
          <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[9.738, 76.578, -58.936]} rotation={[0, -Math.PI / 2, 0]} scale={[11.158, 3.774, 4.456]} />
          <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} position={[17.149, 52.928, -43.613]} rotation={[0, -1.435, 0]} scale={[11.158, 3.774, 4.456]} />
          <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} position={[-124.495, 44.142, -15.335]} rotation={[0, -1.435, 0]} scale={[11.158, 3.774, 4.456]} />
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.podloga} position={[0, -0.181, -5.529]} scale={42.675} />
          <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials.chodnik} position={[13.09, 0.101, -7.803]} scale={[22.005, 12.754, 2.58]} />
          <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials.chodnik} position={[-27.955, -0.063, 6.13]} rotation={[0, Math.PI / 2, 0]} scale={[16.08, 12.754, 2.58]} />
          <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials.chodnik} position={[13.09, 0.159, 18.893]} scale={[22.005, 12.754, 2.58]} />
          <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials.chodnik} position={[-27.955, -0.063, -42.657]} rotation={[0, Math.PI / 2, 0]} scale={[16.08, 12.754, 2.58]} />
        </group>
        <directionalLight intensity={1.9} decay={2} position={[5, 34.498, -5.62]} target={nodes.DirectionalLight.target}>
          <primitive object={nodes.DirectionalLight.target} position={[0, 0, -1]} />
        </directionalLight>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
